// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: spserv.proto

package spserv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_spserv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spserv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_spserv_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_spserv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spserv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_spserv_proto_rawDescGZIP(), []int{1}
}

func (x *PublishRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PublishRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_spserv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_spserv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_spserv_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_spserv_proto protoreflect.FileDescriptor

const file_spserv_proto_rawDesc = "" +
	"\n" +
	"\fspserv.proto\x12\x06spserv\x1a\x1bgoogle/protobuf/empty.proto\"$\n" +
	"\x10SubscribeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"6\n" +
	"\x0ePublishRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"\x1b\n" +
	"\x05Event\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data2\x7f\n" +
	"\x06PubSub\x128\n" +
	"\tSubscribe\x12\x18.spserv.SubscribeRequest\x1a\r.spserv.Event\"\x000\x01\x12;\n" +
	"\aPublish\x12\x16.spserv.PublishRequest\x1a\x16.google.protobuf.Empty\"\x00B7Z5github.com/MaKcm14/vk-test/internal/controller/spservb\x06proto3"

var (
	file_spserv_proto_rawDescOnce sync.Once
	file_spserv_proto_rawDescData []byte
)

func file_spserv_proto_rawDescGZIP() []byte {
	file_spserv_proto_rawDescOnce.Do(func() {
		file_spserv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spserv_proto_rawDesc), len(file_spserv_proto_rawDesc)))
	})
	return file_spserv_proto_rawDescData
}

var file_spserv_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_spserv_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: spserv.SubscribeRequest
	(*PublishRequest)(nil),   // 1: spserv.PublishRequest
	(*Event)(nil),            // 2: spserv.Event
	(*emptypb.Empty)(nil),    // 3: google.protobuf.Empty
}
var file_spserv_proto_depIdxs = []int32{
	0, // 0: spserv.PubSub.Subscribe:input_type -> spserv.SubscribeRequest
	1, // 1: spserv.PubSub.Publish:input_type -> spserv.PublishRequest
	2, // 2: spserv.PubSub.Subscribe:output_type -> spserv.Event
	3, // 3: spserv.PubSub.Publish:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_spserv_proto_init() }
func file_spserv_proto_init() {
	if File_spserv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spserv_proto_rawDesc), len(file_spserv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spserv_proto_goTypes,
		DependencyIndexes: file_spserv_proto_depIdxs,
		MessageInfos:      file_spserv_proto_msgTypes,
	}.Build()
	File_spserv_proto = out.File
	file_spserv_proto_goTypes = nil
	file_spserv_proto_depIdxs = nil
}
